



<form method="post" action="<?php echo App::config('url') ?>/Index/newPost">
    <div class="form-group">
        <label for="content">What's on your mind?</label>
        <input id="content" name="content" type="text"/>
        <button type="submit">Posalji</button>
    </div>

</form>


<?php foreach ($posts as $post): ?>


<p><a href="<?php echo App::config('url')?>/Index/view/<?= $post->getId()?>">
    <?php echo $post->getContent(); ?></a>
</p>



<?php endforeach; ?>