
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
    <head>
        <?php include_once "head.phtml"?>
    </head>
    <body>
        <div class="grid-container">
            <div class="grid-x grid-padding-x">
                <div class="large-12 cell">
                    <?php echo $content ?>
                </div>
            </div>
        </div>
        <?php include_once "skripte.phtml"?>
    </body>
</html>
