
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
<head>
    <?php include_once "head.phtml"?>
</head>
<body>
<div class="grid-container">
    <div class="grid-x grid-padding-x">
        <div class="large-12 cell" style="padding-top: 3cm">
            <h4>Published posts:</h4>
            <p><?php echo $post->getContent()?></p>
            <?php echo $post->getId() ?>
            <form method="post" action="<?php echo App::config('url') ?>Index/deletePost/<?php echo $post->getId() ?>">
                <input type="hidden" id="id" name="id" value="<?php echo $post->getId() ?>">
                <button class="button" type="submit">Delete</button>
            </form>
        </div>
    </div>
</div>
<?php include_once "skripte.phtml"?>
</body>
</html>